default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: history_seeker_development

test:
  <<: *default
  database: history_seeker__test

production:
  <<: *default
  database: history_seeker_production
  username: history
  password: <%= ENV['HISTORY_DATABASE_PASSWORD'] %>
